#!/bin/sh

echo "Montando datos de chaman: /LUSTRE/FORCING/FORECASTS_GOLFOMEX/GLOBAL_ANALYSIS_FORECAST_PHY_001_024"
sshfs chaman.cicese.mx:/LUSTRE/FORCING/FORECASTS_GOLFOMEX/GLOBAL_ANALYSIS_FORECAST_PHY_001_024 mercator-data

